spring:
  application:
    environment: test
  datasource:
    url: jdbc:h2:mem:better
    driver-class-name: org.h2.Driver
    username: better
    password: better
    database-platform: org.hibernate.dialect.H2Dialect